### ISSUE TITLE
Characters flashing on load screen in SPF2T (960529 EURO)

### ISSUE THREAD

**Issue by flab1990** [barry65536/FBAlpha#10]
In Super Puzzle Fighter 2 Turbo, there are times when the chosen character sprites from the character select screen will briefly flash through the loading screen as the match loads. I'm noticing this when I play the game through Retroarch, which is using the 0.2.97.44 version of FBA. It does not occur when playing through Fightcade2, which uses 0.2.97.43. Here's a recording of the issue:

https://giant.gfycat.com/GroundedEcstaticArkshell.webm

Oddly, his will not happen when loading the first match after launch or when loading the first match after continuing. You need to win a match, then subsequent loads will reproduce the issue.

**Comment by dinkc64** [comment]
Hi, thanks for the report, I've reverted the #lines change for the cps just for spf2t, and that fixed the issue.
Basically, we made a change to execute the cpu for the correct number of lines (262), and that fixed a number of gfx glitches across the board (cps1/2).  But this game for some reason doesn't like that.
Funny thing is, the same bug happens in MAME also, so I wonder if this glitch actually happens on the real PCB of spf2t?

**Comment by dinkc64** [comment]
Unfortunately, I can still make it happen sometimes.  Time for a new method of attack :)

**Comment by dinkc64** [comment]
I can now even make this happen in FBA .43.  The reason I didn't see this in .43 at first when I tried to reproduce it was because I had frameskipping on, and the frame with the bad glitch was getting skipped.  Now I'm convinced that this is a bug in the original game code, and there's nothing we can do to fix it :(

![spf_fba43](https://user-images.githubusercontent.com/12570148/50502753-aa650a80-0a2f-11e9-891e-d6cc8bba0b2e.png)

**Comment by flab1990** [comment]
Darn, that's a bummer. Thanks for looking into it.
