### ISSUE TITLE
Unable to load the cdz cover

### ISSUE THREAD

**Issue by LodanZark** [barry65536/FBAlpha#24]
I put the following files into /support/cdz

_shortname_-front.png
_shortname_-back.png
and
_iso_filename_-front.png
_iso_filename_-back.png

Non of those methods work, even define a different cdz cover folder by set it manually and achieved the same results.

**Comment by dinkc64** [comment]
Hi,
Because we couldn't find all of the neogeo cdz cover backs, I changed it to show cd cover front and game preview for the second one.   If you have access to all of the cover "backs", and let me know where to get them, I can change the preview part back to the back cover :)
It should default to support/neocdz, and support/previews
try shortname-front.png in support/neocdz and shortname.png in previews

best regards,
- dink

**Comment by LodanZark** [comment]
It's working, thank you very much!
I do not have all the back covers at moment, but if I can get them I will let ya know ;)

**Comment by dinkc64** [comment]
Nice to hear and thanks :)
